Repository projectcalico/apiserver, pull requests merged in 2021-08, with the labels that each got.

#50 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#52 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#53 Automated cherry pick of #52: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#54 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#55 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#57 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#56 Register resources as internal
  pkg/apiserver/apiserver.go
Labels: docs-pr-required, release-note-required

#58 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#59 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
