Repository projectcalico/apiserver, pull requests merged in 2021-10, with the labels that each got.

#70 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#77 Add IPReservation resource.
  go.mod
  go.sum
  pkg/registry/projectcalico/ipreservation/storage.go
  pkg/registry/projectcalico/ipreservation/strategy.go
  pkg/registry/projectcalico/rest/storage_calico.go
  pkg/storage/calico/converter.go
  pkg/storage/calico/ipreservation_storage.go
  pkg/storage/calico/storage_interface.go
  test/integration/clientset_test.go
Labels: docs-pr-required, release-note-required, merge-when-ready

#80 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required
