Repository projectcalico/apiserver, pull requests merged in 2021-04, with the labels that each got.

#3 Update pins, update k8s version (v0.21.0-rc.0), add protocol shield t…
  .semaphore/update_pins.yml
  Makefile
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/apiserver/protocalshield.go
  pkg/openapi/openapi_generated.go
  pkg/storage/calico/api_object_versioner.go
  pkg/storage/calico/policy_storage_test.go
  pkg/storage/calico/resource.go
  pkg/storage/calico/watcher_test.go
Labels: docs-pr-required, release-note-required

#4 Include build env variables before common makefile include
  Makefile
Labels: docs-not-required, release-note-not-required

#5 Update libcalico-go pins
  go.mod
  go.sum
  pkg/openapi/openapi_generated.go
Labels: docs-not-required, release-note-not-required

#8 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#9 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#7 Make cluster information read-only
  .gitignore
  pkg/registry/projectcalico/clusterinformation/storage.go
  pkg/storage/calico/clusterInformation_storage.go
  test/integration/clientset_test.go
Labels: docs-not-required, release-note-not-required

#10 Fix release-build to hit the correct common Makefile targets
  Makefile
Labels: docs-not-required, release-note-not-required
